---
title: "Experiment 2: Codes for handling and analising sea temperature and Chla"
author: "André Pardal"
date: "10 November 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Loading packages
```{r loading data}

library(ggplot2)
library(ggpubr)
library(dplyr)
library(openxlsx)  
library(readxl)
library(dplyr)
library(plyr)
library(forcats)
library(tidyverse)
library(grid)
library(xlsx)
library(writexl)
library(ggeffects)

setwd("~/Desktop/Chapter 2/submission/Oecologia/Review-9-21/Github/data")
dir()
```


#### Temperature: loggers and satellite data (you can skip to the next chunk)
```{r aggregating data}

## Loggers
temp_loggers <- read_excel("Pardal-2021-temperature-rev.xlsx", sheet = 2)
str(temp_loggers)

temp_loggers$site         <- as.factor(temp_loggers$site)
temp_loggers$dateYYYYMMdd <- as.Date(temp_loggers$dateYYYYMMdd)

str(temp_loggers)

temp_loggers_agg1 <- aggregate(temp_C ~ site, mean, data = temp_loggers)
temp_loggers_sd   <- aggregate(temp_C ~ site, sd, data = temp_loggers)
temp_loggers_agg2 <- aggregate(temp_filt ~ site, mean, data = temp_loggers)

## aggregating filtered logger temperature by date and site:
temp_log_filt_date <- aggregate(temp_filt ~ site + dateYYYYMMdd, mean, data = temp_loggers)
abc                <- aggregate(temp_filt ~ site, mean, data = temp_log_filt_date)

#write.xlsx(temp_log_filt_date, file = "temp-logger-filtered.xlsx",
           #sheetName = "temp-filt", append = FALSE)


## Satellite data:
sst_sat <- read_excel("Pardal-2021-temperature-rev.xlsx", sheet = 3)
str(sst_sat)

sst_sat$site         <- as.factor(sst_sat$site)
sst_sat$dateYYYYMMdd <- as.Date(sst_sat$dateYYYYMMdd)

str(sst_sat)

sst_agg <- aggregate(sst ~ site + dateYYYYMMdd, mean, data = sst_sat)

#write.xlsx(sst_agg, file = "sst_agg.xlsx",
          # sheetName = "sst_agg", append = FALSE)
```


#### Supplementary fig: filtered logger temperature
```{r Plotting supplementary figure with filtered data}

#### Figures temperature ####
#### Supplementary figure showing the measured and filtered data from loggers ####
## For each site, values < mean-1.5SD & > mean+1.5SD were deleted (considered air temperature) ##

temp_fig_sup <- read_excel("Pardal-2021-temperature-rev.xlsx", sheet = 4)
str(temp_fig_sup)

temp_fig_sup$site         <- as.factor(temp_fig_sup$site)
temp_fig_sup$temp_type    <- as.factor(temp_fig_sup$temp_type)
temp_fig_sup$dateYYYYMMdd <- as.Date(temp_fig_sup$dateYYYYMMdd)

temp_fig_sup$site <- factor(temp_fig_sup$site, 
                            levels = c("Iporanga", "Itassuce", "P. Grande", 
                                       "Grumari", "Piratininga", "Fortaleza"))

temp_fig_sup$temp_type <- factor(temp_fig_sup$temp_type, 
                                 levels = c("air temperature", "sea temperature"))
  
 ggplot(temp_fig_sup, aes(x=dateYYYYMMdd, 
                          group = site, 
                          y=temp_C, 
                          fill = temp_type, 
                          colour = temp_type)) + 
  theme_classic()+ 
  geom_point(size=1., alpha=.95) + 
  facet_wrap(~site, ncol = 2)+
  scale_colour_manual(values = c("darkcyan", "tomato2"))+
  #geom_smooth(colour = "black")+
  theme(axis.text.x = element_text(size=12, color="black"), 
        axis.text.y = element_text(size=12, color="black"),
        axis.title.x = element_text(color="black", size=14),
        axis.title.y = element_text(color="black", size=14))+
  labs(x = "", 
       y = expression(paste("logger temperature (°C)")))+
  theme(strip.text.x = element_text(size = 12), 
        strip.text.y = element_text(size = 12)) +
  theme(legend.position = "bottom") + 
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks.length = unit(4, "pt"))+
  theme(legend.position = c(.02, .95),
        legend.justification = c("left"),
        legend.box.just = "left",
        legend.margin = margin(0, 0, 0, 0)) + 
   theme(legend.title = element_text(color = "white", size = 5),
          legend.text = element_text(color = "black", size = 11))## 

#ggsave("temp-loggers-supp.png", width = 9.87, height = 7.01, units = "in", dpi = 300)
#Saving 9.87 x 7.01 in image
```


#### Supplementary fig: Satellite SST bias
```{r SST bias}

sst_bias <- read_excel("Pardal-2021-temperature-rev.xlsx", sheet = 6)
str(sst_bias)

sst_bias$site        <- as.factor(sst_bias$site)
sst_bias$dateYYYMMdd <- as.Date(sst_bias$dateYYYMMdd)

sst_bias$sst_bias <- (sst_bias$sst_satellite) - (sst_bias$temp_logger)
bias_agg          <- aggregate(sst_bias ~ site, mean, data = sst_bias)

sst_bias$site <- factor(sst_bias$site, 
                           levels = c("Iporanga", "Itassucê", "P. Grande", 
                                      "Grumari", "Piratininga", "Fortaleza"))

bias_fig <-  
  ggplot(sst_bias, aes(y= sst_bias, x= site))+ 
  geom_jitter(height = 0, width = 0.1, 
              size=2.,    alpha=0.25) + 
  stat_summary(fun.data="mean_se",  
               fun.args = list(mult=1), 
               geom="pointrange", 
               size=1.3)+
  theme_classic() + 
  theme(axis.text.x = element_text(size=16, 
                                   color ="black", 
                                   angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1), 
         axis.text.y = element_text(size = 16, 
                                     color = "black"),
         axis.title.x = element_text(color = "black", 
                                      size = 16),
         axis.title.y = element_text(color = "black", 
                                      size = 16))+ 
  labs(x = "", 
       y = expression(paste("Satellite SST bias (°C)")))+ 
  #scale_color_manual(values=c('black','red'))+ 
  theme(strip.text.x = element_text(size = 12), 
        strip.text.y = element_text(size = 12))+ 
  theme(legend.position = "none") +
  theme(axis.ticks = element_line(colour = "black", 
                                  size = 0.8)) + 
  theme(axis.line = element_line(colour = 'black', 
                                 size = 0.8)) + 
  theme(axis.ticks.length = unit(4, "pt"))+
  scale_x_discrete(label = c("Iporanga", "Itassucê", "P. Grande",
                             "Grumari", "Piratininga", "Fortaleza")) 

bias_fig
#ggsave("SST-satellite-bias.svg", dpi = 300)
```


#### Plotting data logger temp vs. satellite SST
```{r Match-up}

sat_ibutton <- read_excel("Pardal-2021-temperature-rev.xlsx", sheet = 6)
str(sat_ibutton)
#sat_ibutton2 = sat_ibutton %>% drop_na() ## dropping NA values ##

## linear model (temp ibutton ~ sst satellite) ##
mod1 <- lm( sst_satellite ~ temp_logger, data = sat_ibutton) 
summary(mod1)## Global: slope = 0.76***, R^2 = 0.47, N = 144

#RMSE(y_pred = mod1$fitted.values, y_true = sat_ibutton2$temp_ibutton) ## calculating RMSE (root square of std error) ##
## RMSE = 0.8766887 ##

mod2 <- lm(sst_satellite ~ temp_logger, data = (subset(sat_ibutton, site == "Iporanga")))
summary(mod2)## Iporanga: slope 0.76***, R^2 = 0.56, N = 21

mod3 <- lm(sst_satellite ~ temp_logger, data = (subset(sat_ibutton, site == "Itassucê")))
summary(mod3)## Itassucê: slope 0.80***, R^2 = 0.66, N = 21

mod4 <- lm(sst_satellite ~ temp_logger, data = (subset(sat_ibutton, site == "P. Grande")))
summary(mod4)## P. Grande: slope 0.99***, R^2 = 0.46, N = 18

mod5 <- lm(sst_satellite ~ temp_logger, data = (subset(sat_ibutton, site == "Grumari")))
summary(mod5)## Grumari: slope 0.69**, R^2 = 0.30, N = 25

mod6 <- lm(sst_satellite ~ temp_logger, data = (subset(sat_ibutton, site == "Piratininga")))
summary(mod6)## Piratininga: slope 0.45 ***, R^2 = 0.45, N = 29

mod7 <- lm(sst_satellite ~ temp_logger, data = (subset(sat_ibutton, site == "Fortaleza")))
summary(mod7)## Fortaleza: slope 0.64***, R^2 = 0.14, N = 30

###### Plots ######
sat_ibutton$site <- factor(sat_ibutton$site, 
                           levels = c("Iporanga", "Itassucê", "P. Grande", 
                                      "Grumari", "Piratininga", "Fortaleza"))

 validation1 <-
  ggplot(sat_ibutton, aes(x = temp_logger, 
                          y = sst_satellite, 
                          colour = site, 
                          fill = site)) + 
  theme_classic()+ 
  geom_smooth(method = lm, se = F, fullrange = F)+ 
  geom_point(size=3)+
  theme(axis.text.x = element_text(size=12, color="black"), 
        axis.text.y = element_text(size=12, color="black"),
        axis.title.x = element_text(color="black", size=14),
        axis.title.y = element_text(color="black", size=14))+
  labs(x = "data logger SST (°C)", 
       y = expression(paste("satellite SST (°C)")))+
  theme(strip.text.x = element_text(size = 12), 
        strip.text.y = element_text(size = 12))+
  theme(legend.position = "bottom") + 
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks.length = unit(4, "pt"))+
  scale_colour_viridis_d(option = "viridis") + 
  xlim(20,26) + 
  ylim(20,26) +
   theme(legend.title = element_text(color = "white", size = 5),
         legend.text = element_text(color = "black", size=11))

 validation1 <-
        validation1  +  
        theme(legend.position = c(.02, .80),
              legend.justification = c("left"), 
              legend.box.just = "left",
              legend.margin = margin(0, 0, 0, 0)) + 
        theme(legend.title = element_text(color = "white", size = 5),
              legend.text = element_text(color = "black", size=10))
 
validation1
############
 
  validation2 <-
  ggplot(sat_ibutton, aes(x= temp_logger, y = sst_satellite)) + 
    theme_classic()+ 
    geom_smooth(method = lm, se = T, fullrange = T)+ 
    geom_point(size = 3)+
  theme(axis.text.x = element_text(size=12, color="black"), 
        axis.text.y = element_text(size=12, color="black"),
        axis.title.x = element_text(color="black", size=14),
        axis.title.y = element_text(color="black", size=14))+
  labs(x = "data logger SST (°C)", 
       y = expression(paste("satellite SST (°C)")))+
  theme(strip.text.x = element_text(size = 12), 
        strip.text.y = element_text(size = 12))+
  theme(legend.position = "bottom") + 
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks.length = unit(4, "pt"))+
  theme(legend.title = element_text(color = "white", size = 5),
         legend.text = element_text(color = "black", size=11)) +
    xlim(20,26) + ylim(20,26)

validation2
############
 
sst_val <- ggarrange(validation2, validation1, ncol = 1, nrow = 2, align = "hv")
sst_val

#ggsave("sst_validation.svg", dpi = 400, width = 5, height =10, units= "in")
```


#### SST final figure 
```{r Fig SST final}

temp_log_sat= read_excel("Pardal-2021-temperature-rev.xlsx", sheet = 5)
str(temp_log_sat)

temp_log_sat$site = as.factor(temp_log_sat$site)
temp_log_sat$source = as.factor(temp_log_sat$source)
temp_log_sat$dateYYYYMMdd = as.Date(temp_log_sat$dateYYYYMMdd)

temp_log_sat$site = factor(temp_log_sat$site, levels = c("Astúrias", "Iporanga", "Itassucê", "Zimbro", "P. Vermelha", 
                                                         "P. Grande", "Grumari", "Piratininga","Fortaleza", "Prainha"))

sst_final =  
  ggplot(temp_log_sat, aes(y= temp_final, x= site))+ 
  #geom_jitter(height = 0, 
             # width = 0.1, 
             # size=2.3, 
             # alpha=0.25) + 
  stat_summary(fun.data="mean_se",  
               fun.args = list(mult=1), 
               geom="pointrange", 
               size=1.7, aes(color=source))+
  theme_classic() + 
  theme(axis.text.x = element_text(size=16, 
                                   color="black", 
                                   angle= 90, 
                                   vjust = 0.5, 
                                   hjust = 1), 
         axis.text.y = element_text(size=16, 
                                     color="black"),
         axis.title.x = element_text(color="black", 
                                      size=16),
         axis.title.y = element_text(color="black", 
                                      size=16))+ 
  labs(x = "", 
       y = expression(paste("sea temperature (°C)")))+ 
  scale_color_manual(values=c('tomato2','black'))+ 
  theme(strip.text.x = element_text(size = 12), 
        strip.text.y = element_text(size = 12))+ 
  theme(legend.position = "none") +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) + 
  theme(axis.line = element_line(colour = 'black', size = 0.8)) + 
  theme(axis.ticks.length = unit(4, "pt"))+
  scale_x_discrete(label = c("Astúrias", "Iporanga", "Itassucê", 
                             "Zimbro", "P. Vermelha", "P. Grande",
                             "Grumari", "Piratininga", "Fortaleza", "Prainha")) +
  scale_y_continuous(breaks = seq(21.6, 23.4, by = 0.4))

sst_final
```


#### Chla figure
```{r }

chla1 <- read_excel("Pardal-2021-temperature-rev.xlsx", sheet = 7)
str(chla1)

chla1$site         <- as.factor(chla1$site)
chla1$dateYYYYMMdd <- as.Date(chla1$dateYYYYMMdd)

chla2 <- aggregate(Chla ~ dateYYYYMMdd + site, mean, data = chla1)

chla2$site  <- factor(chla2$site , levels = c("Asturias", "Iporanga", "Itassuce", "Zimbro", "P. Vermelha", 
                                              "P. Grande", "Grumari", "Piratininga","Fortaleza", "Prainha"))

chla_final <-  
  ggplot(chla2, aes(y= Chla, x= site))+ 
  #geom_jitter(height = 0, 
             # width = 0.1, 
             # size=2.3, 
             # alpha=0.25) + 
  stat_summary(fun.data = "mean_se",  
               fun.args = list(mult=1), 
               geom = "pointrange", 
               size=1.7)+
  theme_classic() + 
  theme(axis.text.x = element_text(size = 16, 
                                   color = "black", 
                                   angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1), 
         axis.text.y = element_text(size = 16, 
                                     color = "black"),
         axis.title.x = element_text(color = "black", 
                                      size = 16),
         axis.title.y = element_text(color="black", 
                                      size=16))+ 
  labs(x = "", 
       y = bquote('satellite Chla ('~mg.m^-3~')')) + 
  scale_color_manual(values=c('black','red'))+ 
  theme(strip.text.x = element_text(size = 12), 
        strip.text.y = element_text(size = 12))+ 
  theme(legend.position = "none") +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) + 
  theme(axis.line = element_line(colour = 'black', size = 0.8)) + 
  theme(axis.ticks.length = unit(4, "pt"))+
  scale_x_discrete(label = c("Astúrias", "Iporanga", "Itassucê", 
                             "Zimbro", "P. Vermelha", "P. Grande",
                             "Grumari", "Piratininga", "Fortaleza", "Prainha")) #+
  #scale_y_continuous(breaks = seq(21.6, 23.4, by = 0.4))

chla_final

ggarrange(chla_final, sst_final, ncol = 1, nrow = 2, align = "hv")
#ggsave("Chla_SST_final.svg", dpi = 400, width = 190, height = 240, units = "mm") ## Okay
```
